### ISSUE TITLE
TypeError in Global Error Trapper

### ISSUE THREAD

**Issue by Salvamontess** [thkruz/keeptrack.space#599]
#### User Description
Type what you were trying to do here...

#### Error Title
TypeError
#### Error Message
Cannot read properties of null (reading 'style')
#### Stack
TypeError: Cannot read properties of null (reading 'style')
    at be (https://www.keeptrack.space/js/main.63fa6755769926409a9c.js:3032:15644)
    at https://www.keeptrack.space/js/main.63fa6755769926409a9c.js:3032:15435

**Comment by thkruz** [comment]
Error is in ```getEl('loading-earth').style.display = 'none';``` in hideLoadingScreen.ts

loading-earth is no longer used. Fixed for the next patch coming tomorrow.

This error only exists on mobile. Need to decide if I am going to continue supporting mobile, because I am not doing a great job supporting it at the moment. Maybe a static info page is needed as a redirect when on mobile...

**Comment by thkruz** [comment]
Fixed
